In [1]:
import pickle
import numpy as np
import os
import scipy.sparse as sp
import torch
from scipy.sparse import linalg
from torch.autograd import Variable
import os

In [2]:
file_name = os.getcwd() + "/solar_AL.txt"
fh = open(file_name,'r')

In [3]:
raw_data = np.loadtxt(fh, delimiter=",")

In [4]:
raw_data.shape[1]

137

In [5]:
scaled_cols = np.ones(m)

NameError: name 'm' is not defined

In [64]:
scaled_cols

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [80]:
normalized_data = np.zeros(raw_data.shape)
for i in range(m):
    scaled_cols[i] = np.max(np.abs(raw_data[:,i]))
    normalized_data[:,i] = raw_data[:,i] / np.max(np.abs(raw_data[:,i]))

In [81]:
scaled_cols

array([58.85, 33.35, 33.35, 33.15, 48.5 , 88.9 , 28.95, 29.3 , 33.4 ,
       33.  , 30.35, 16.95, 32.7 , 33.1 , 36.1 , 16.4 , 34.85, 31.85,
       32.9 , 32.5 , 34.45, 35.3 , 33.55, 71.  , 32.5 , 28.2 , 31.5 ,
       31.5 , 73.  , 33.15, 26.8 , 59.75, 33.2 , 30.3 , 30.8 , 26.35,
       32.65, 23.75, 32.55, 32.95, 80.65, 32.6 , 33.85, 31.35, 41.75,
       24.65, 24.35, 30.75, 31.85, 32.9 , 34.85, 32.75, 32.75, 33.25,
       29.15, 32.5 , 34.75, 29.4 , 30.1 , 33.7 , 24.1 , 32.6 , 31.15,
       30.45, 30.35, 32.15, 32.65, 32.4 , 59.55, 62.4 , 46.15, 22.75,
       31.  , 81.3 , 32.3 , 31.9 , 35.95, 30.25, 34.85, 30.4 , 44.05,
       31.6 , 28.55, 23.05, 31.7 , 29.35, 32.6 , 30.15, 28.45, 29.15,
       21.9 , 29.5 , 34.45, 30.5 , 29.  , 30.6 , 24.6 , 28.8 , 27.85,
       31.9 , 24.35, 23.8 , 31.95, 31.7 , 54.35, 50.85, 31.55, 33.4 ,
       29.35, 32.65, 32.45, 32.9 , 17.6 , 28.3 , 30.9 ,  8.8 , 33.5 ,
       31.45, 33.15, 24.05, 34.5 , 68.7 , 32.55, 34.3 , 53.95, 44.05,
       18.75, 31.35,

In [41]:
raw_data[9000,:]

array([48.05, 27.75, 27.9 , 26.95, 37.9 , 77.75, 22.7 , 26.3 , 28.25,
       28.05, 26.05, 15.7 , 27.75, 27.15, 32.9 , 12.15, 27.  , 29.5 ,
       28.2 , 27.7 , 30.7 , 28.7 , 24.25, 64.65, 25.25, 24.65, 27.35,
       27.25, 58.7 , 26.15, 19.2 , 59.75, 28.85, 24.95, 24.3 , 23.7 ,
       29.1 , 21.4 , 28.  , 26.55, 71.45, 27.8 , 28.4 , 23.5 , 34.75,
       19.65, 20.95, 24.3 , 28.05, 29.15, 28.2 , 28.6 , 25.7 , 27.15,
       25.5 , 28.05, 26.65, 23.65, 25.2 , 28.5 , 20.25, 28.1 , 26.85,
       24.65, 24.2 , 32.05, 27.75, 30.15, 43.  , 51.85, 39.75, 19.95,
       22.4 , 66.2 , 26.9 , 27.65, 31.95, 25.35, 28.75, 26.55, 37.8 ,
       28.1 , 23.35, 20.  , 28.  , 27.75, 25.55, 25.5 , 23.05, 24.95,
       18.35, 24.35, 29.45, 24.7 , 26.4 , 24.75, 18.85, 25.55, 18.65,
       29.35, 20.3 , 20.3 , 26.75, 27.05, 42.25, 43.6 , 26.65, 27.3 ,
       25.2 , 28.7 , 26.7 , 27.1 , 16.8 , 25.95, 28.55,  6.8 , 27.05,
       26.85, 28.1 , 20.05, 28.15, 50.4 , 27.3 , 29.05, 44.8 , 38.85,
       15.3 , 25.3 ,

In [42]:
normalized_data[9000,:]

array([0.81648258, 0.83208396, 0.83658171, 0.81297134, 0.7814433 ,
       0.87457818, 0.78411054, 0.89761092, 0.84580838, 0.85      ,
       0.8583196 , 0.92625369, 0.84862385, 0.82024169, 0.91135734,
       0.74085366, 0.77474892, 0.92621664, 0.85714286, 0.85230769,
       0.89114659, 0.81303116, 0.72280179, 0.91056338, 0.77692308,
       0.87411348, 0.86825397, 0.86507937, 0.80410959, 0.78883861,
       0.71641791, 1.        , 0.8689759 , 0.82343234, 0.78896104,
       0.89943074, 0.89127106, 0.90105263, 0.86021505, 0.80576631,
       0.88592684, 0.85276074, 0.83899557, 0.74960128, 0.83233533,
       0.79716024, 0.86036961, 0.7902439 , 0.88069074, 0.88601824,
       0.80918221, 0.87328244, 0.78473282, 0.81654135, 0.87478559,
       0.86307692, 0.76690647, 0.80442177, 0.8372093 , 0.84569733,
       0.84024896, 0.86196319, 0.86195827, 0.80952381, 0.79736409,
       0.99688958, 0.84992343, 0.93055556, 0.72208228, 0.83092949,
       0.86132178, 0.87692308, 0.72258065, 0.81426814, 0.83281

In [65]:
window = 24*7
horizon = 3
vars = m

train_ratio = 0.6
val_ratio = 0.2

train_set = range(window+horizon-1, int(train_ratio*n))
val_set = range(int(train_ratio*n), int((train_ratio+val_ratio)*n))
test_set = range(int((train_ratio+val_ratio)*n),n)

In [46]:
print(train_set)

range(170, 31536)


In [49]:
train_set[0]

170

In [68]:
train_samples = len(train_set)
X_train = torch.zeros((train_samples, window, vars))
Y_train = torch.zeros((train_samples, vars))

for i in range(train_samples):
    end = train_set[i] - horizon + 1
    start = end - window
    if i==0 or i==train_samples-1:
        print(f"End index:{end}")
        print(f"Start index:{start}\n")
    X_train[i,:,:] = torch.from_numpy(normalized_data[start:end,:])
    Y_train[i,:] = torch.from_numpy(normalized_data[train_set[i],:])

End index:168
Start index:0

End index:31533
Start index:31365



In [88]:
X_train.shape

torch.Size([31366, 168, 137])

In [69]:
val_samples = len(val_set)
X_val = torch.zeros((val_samples, window, vars))
Y_val = torch.zeros((val_samples, vars))

for i in range(val_samples):
    end = val_set[i] - horizon + 1
    start = end - window
    if i==0 or i==val_samples-1:
        print(f"End index:{end}")
        print(f"Start index:{start}\n")
    X_val[i,:,:] = torch.from_numpy(normalized_data[start:end,:])
    Y_val[i,:] = torch.from_numpy(normalized_data[val_set[i],:])

End index:31534
Start index:31366

End index:42045
Start index:41877



In [70]:
test_samples = len(test_set)
X_test = torch.zeros((test_samples, window, vars))
Y_test = torch.zeros((test_samples, vars))

for i in range(test_samples):
    end = test_set[i] - horizon + 1
    start = end - window
    if i==0 or i==test_samples-1:
        print(f"End index:{end}")
        print(f"Start index:{start}\n")
    X_test[i,:,:] = torch.from_numpy(normalized_data[start:end,:])
    Y_test[i,:] = torch.from_numpy(normalized_data[test_set[i],:])

End index:42046
Start index:41878

End index:52557
Start index:52389



In [72]:
Y_test.size(0)

10512

In [82]:
scaled_cols = torch.from_numpy(scaled_cols).float()
tmp = Y_test * scaled_cols.expand(Y_test.size(0), m)

In [94]:
tmp

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [85]:
rse = tmp.std() * np.sqrt((len(tmp) - 1.) / len(tmp))
rae = torch.mean(torch.abs(tmp - torch.mean(tmp)))

print(rse)

print(rae)

tensor(8.9212)
tensor(6.5985)


In [89]:
X_train.shape

torch.Size([31366, 168, 137])

In [90]:
X_unsqueezed = torch.unsqueeze(X_train, dim=1)

In [93]:
X_unsqueezed = X_unsqueezed.transpose(2,3)
X_unsqueezed.shape

torch.Size([31366, 1, 137, 168])

In [96]:
import torch
import torch.nn.functional as F

# Create an example tensor
tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

# Define the padding
# (pad_left, pad_right, pad_top, pad_bottom)
padding = (1, 1, 2, 2)

# Apply padding
padded_tensor = F.pad(tensor, padding, mode='constant', value=0)

print("Original tensor:")
print(tensor)

print("Padded tensor:")
print(padded_tensor)



Original tensor:
tensor([[1., 2.],
        [3., 4.]])
Padded tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 1., 2., 0.],
        [0., 3., 4., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [86]:
# import pandas as pd
# raw_data_pd = pd.read_csv("C:/Users/schakr18/Downloads/solar_AL.csv", header=None)
# raw_data_pd.head()