In [1]:
import torch
import torch.nn as nn

# Define an embedding layer for a vocabulary of size 10 with embedding dimension 3
embedding = nn.Embedding(10, 3)

# Example input: indices of words in the vocabulary
input_indices = torch.LongTensor([1, 2, 3, 4])

# Get the corresponding embeddings
output = embedding(input_indices)
print(output)

tensor([[ 1.2137,  0.5327,  1.5255],
        [ 1.1486, -0.1278,  1.8731],
        [ 0.4105,  0.1860,  1.2737],
        [ 1.9408,  0.5079,  0.7463]], grad_fn=<EmbeddingBackward0>)


In [3]:
import torch

# Create a tensor (matrix)
matrix = torch.Tensor([[1, 2, 3],
                       [4, 5, 6]])

# Create a new tensor with the same shape as 'matrix', filled with random numbers
random_tensor = torch.rand_like(matrix)

# Print the original matrix
print("Original matrix:")
print(matrix)

# Print the random tensor
print("\nRandom tensor:")
print(random_tensor)


Original matrix:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Random tensor:
tensor([[0.5255, 0.0561, 0.3567],
        [0.7196, 0.9255, 0.0578]])


In [22]:
import torch
import numpy as np

# Create a tensor to scatter values into
tensor = torch.zeros(3, 5)
tensor2 = torch.zeros(3, 5)

# Indices where we want to scatter values
indices = torch.tensor([[0, 1, 2, 0, 1],
                        [1, 2, 0, 1, 2],
                        [2, 0, 1, 2, 0]])
print(indices)

# Values to scatter
values = torch.from_numpy(np.arange(1, 16)).float().view(3, 5)
print(values)

# Perform the scatter operation
tensor.scatter_(1, indices, values)

print("Resulting tensor after scatter_ operation:")
print(tensor)


tensor([[0, 1, 2, 0, 1],
        [1, 2, 0, 1, 2],
        [2, 0, 1, 2, 0]])
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])
Resulting tensor after scatter_ operation:
tensor([[ 4.,  5.,  3.,  0.,  0.],
        [ 8.,  9., 10.,  0.,  0.],
        [15., 13., 14.,  0.,  0.]])
